timeout: 3
verbose: yes

/uACPI
    protocol: limine
    kernel_path: boot():/kernel.elf

/uACPI - Debug
    protocol: limine
    kernel_path: boot():/kernel.elf
    kernel_cmdline: --uacpi-log-level=debug
